### ISSUE TITLE
The issue is about not working properly on Windows 7

### ISSUE THREAD

**Issue by kanghanqiu** [CodeDead/Advanced-PortChecker#1]
**Describe the bug**

Hello  Alessandro Mercier,
First of all, thank you very much for your previous reply.When the software was used on Windows 7, the number of the Starting and Ending ports could not be arbitrarily modified.I realize the problem won't be solved so easily.If you have the latest progress, I still hope to get your timely reply.Thanks again!
Kind regards 

**Desktop (please complete the following information):**
 - OS: [ Windows7]
 - Version [1.5.0.0]

**Comment by CodeDead** [comment]
Windows 7 is no longer supported. A newer OS is recommended.
