### ISSUE TITLE
There are problems in Chinese translation

### ISSUE THREAD

**Issue by 2031301686** [CodeDead/Advanced-PortChecker#14]
There are problems in Chinese translation
(Started port) Translation to (开始端口)
(Port) Translation to (端口)
(Clear) Translation to (清空)
(Export) Translation to (导出)
There is another question, is there no UDP scan, the old version is there

**Comment by CodeDead** [comment]
Hi,

Thanks for bringing this to our attention!

Could you (or someone in the community) perhaps help with these translations by changing them to what they should be? We rely on community translations and do not have a native Chinese speaker who can correct or check these.

In relation to the UDP scanning being removed: This is because UDP scanning is useless when checking for open ports. It is unreliable, and not indicative enough.

Kind regards

**Comment by 2031301686** [comment]
Thank you for replying to this question, but I am not a professional. I may not know how to do it, but I just build a station.
Thank you very much for your development, it is helpful to me. I have my own website blog, and I will share this program with my fans. I believe that other Chinese developers will notice this program and help translate.
In fact, the translation of machine translation has little impact on me, but it is found that the project has added Chinese translation, but there are some errors. If Chinese users use this program without fixing the error translation, these error translations should not be used because they should not affect their meaning.
Regarding UDP, I used the old version before, and then I supported UDP scanning, and I can correctly detect whether the UDP port has been opened
My English is not very good. Our communication is performed through translation tools. After all, the machine is just a machine. There may be problems in the expression. Please forgive me.

**Comment by 2031301686** [comment]
If you just translate this file, maybe I can help, but what should I do, what should I do /src/languages/zh_cn.json

**Comment by CodeDead** [comment]
Thank you for your willingness to help, first of all and for displaying this application on your website!

I understand that we are using tools to improve our communication and we will do our best to avoid any conflicts or problems by knowing this.

It is indeed these files located here, that contain the translations:
https://github.com/CodeDead/Advanced-PortChecker/tree/master/src/languages

If you, for example, edit the zh_cn.json file, with the correct values (on the right side, the English keys should remain unchanged), you might be able to open a pull request with the proper translations. I will also ask for additional help for the Chinese translations too.

https://github.com/CodeDead/Advanced-PortChecker/blob/master/src/languages/zh_cn.json

The values between the quotes on the right side are the translations. If you could point out or edit the wrong ones, I would be very grateful for your help and we will give you the appropriate credits in the application about screen to mark your contributions to these translations!

Kind regards

**Comment by 2031301686** [comment]
I created the branch and modified the translation, published here
https://github.com/CodeDead/Advanced-PortChecker/pull/15/commits

**Comment by CodeDead** [comment]
You are a life saver. Thank you! Could you have a look at the request for adding your name to the credits?

**Comment by CodeDead** [comment]
![image](https://github.com/CodeDead/Advanced-PortChecker/assets/16293330/95549ac6-1af2-4b18-a927-24fa2aae2672)

Small preview of your changes which will go live soon.

**Comment by 2031301686** [comment]
&nbsp;The developer speed is really fast. Thumbs up.👍






---Original---
From: ***@***.***&gt;
Date: Fri, Mar 22, 2024 00:32 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [CodeDead/Advanced-PortChecker] There are problems in Chinesetranslation (Issue #14)




 
image.png (view on web)
 
Small preview of your changes which will go live soon.
