### ISSUE TITLE
Readme github home page - Update info about languages available

### ISSUE THREAD

**Issue by bovirus** [CodeDead/Advanced-PortChecker#22]
@CodeDead 

Please add in home page info about language available (not onluy chinese)

Dutch
French
Italian
Spanish

and info about relative translators.

**Comment by CodeDead** [comment]
Hi,

Dutch, French and Spanish are all provided by me. So it would be odd to add credits to myself.
Italian hasn't been merged yet but rest assured that credits will be given to you once the appropriate info has been added to the PR 😉.

Kind regards
